### ISSUE TITLE
Why not PR into the original extension?

### ISSUE THREAD

**Issue by mcanouil** [shafayetShafee/include-code-files#1]
Since you only add an option, why make a new extension and not improve the existing one with a PR? 🤔

**Comment by shafayetShafee** [comment]
Yes, I had started with a [PR](https://github.com/quarto-ext/include-code-files/pull/2) to the original one initially 🙂. But to incorporate the `code-fold`-ing I had to make a lot of changes in the extension lua file and the original one is simpler to use if you do not want  the code-folding, the original `include-code-files` author [also agreed](https://github.com/quarto-ext/include-code-files/pull/2#issuecomment-1414133329) to implement this feature as another extension.

**Comment by mcanouil** [comment]
Oh I see.
Maybe, mention in the readme that your extension is not really an extension of, but rather an alternative to, with more capabilities.
This "little" wording changes what is the behaviour you might expect from the extension.

**Comment by shafayetShafee** [comment]
Thank you for the suggestion and I have updated the readme. Please let me know if there is anything confusing or anything that can be improved 😊.

**Comment by mcanouil** [comment]
I think it's good, this should avoid confusion and better highlight that you provide a complete extension with improved features.
