### ISSUE TITLE
More explicit installation instructions are needed: code does not work out of the box

### ISSUE THREAD

**Issue by GegznaV** [shafayetShafee/include-code-files#2]
Documentation says:
![image](https://user-images.githubusercontent.com/12725868/224486058-78ae046e-8789-4fc2-99f9-52d4d466bfb1.png)

More explicit instructions are needed as (in terminal):

![image](https://user-images.githubusercontent.com/12725868/224485986-4aaada66-0d68-45d5-98e2-cf49a0691d0f.png)

**Comment by GegznaV** [comment]
By the way, really useful extension. Thanks :)

**Comment by shafayetShafee** [comment]
Oopps! Theres a typo in the installation command. Try with the following,

```
quarto add shafayetShafee/add-code-files
```

I will update the readme asap!

**Comment by shafayetShafee** [comment]
fixed in 0572ab02
